---
# tasks file for ansible-role-bounca/
- name: Install base packages
  apt:
    pkg: 
      - gettext
      - python3
      - python3-dev
      - python3-setuptools
      - uwsgi
      - uwsgi-plugin-python3
      - ntp
      - git
      - virtualenv
      - python3-virtualenv
      - python3-pip
    state: present

- name: Set the correct timezone
  file: 
    src: "{{ bounca_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

- name: Ensure NTP is running and enabled at system start.
  service:
    name: ntp
    enabled: yes
    state: started

- name: Create directory /opt/bounca/cron/scripts
  file:
    path: /opt/bounca/cron/scripts
    state: directory 
  
- name: Copy ntp monitor script
  copy: 
    src: scripts/ntpd_monitor.sh
    dest: /opt/bounca/cron/scripts/ntpd_monitor.sh
    mode: 755

- name: Add cronjobs for ntp_monitor
  cron:
    name: "ntp monitor"
    user: root
    minute: "*/1"
    job: "/opt/bounca/cron/scripts/ntpd_monitor.sh"

- name: Checkout git repo BounCA
  git:
    repo: https://github.com/repleo/bounca.git
    dest: /srv/www/bounca
    force: yes
    version: "{{ bounca_version }}"

- name: Install bounca requirements
  pip: 
    requirements: /srv/www/bounca/requirements.txt
    virtualenv: /srv/www/bounca/env
    virtualenv_python: python3

- name: Set username of app directory
  file:
    path: /srv/www/bounca
    owner: www-data
    group: www-data
    mode: 755
    recurse: yes

- name: Create directory /etc/bounca
  file:
    path: /etc/bounca
    owner: www-data
    group: www-data
    state: directory

- name: Copy bounca config 
  template:
    src: bounca/main.ini
    dest: /etc/bounca/main.ini
    owner: www-data
    group: www-data
    mode: 600

- name: Copy uwsgi config 
  copy:
    src: uwsgi/bounca.ini
    dest: /etc/uwsgi/apps-available/bounca.ini

- name: Create uwsgi symlink
  file:
    src: /etc/uwsgi/apps-available/bounca.ini
    dest: /etc/uwsgi/apps-enabled/bounca.ini
    state: link

- name: Stop uwsgi
  service:
    name: uwsgi
    state: stopped

- name: Migrate django database
  django_manage: 
    command: "migrate --noinput"
    app_path: /srv/www/bounca
    virtualenv: /srv/www/bounca/env

- name: Start uwsgi and enable at boot
  service:
    name: uwsgi
    state: restarted
    enabled: yes
  
- name: Collect static files
  django_manage:
    command: "collectstatic --noinput"
    app_path: /srv/www/bounca
    virtualenv: /srv/www/bounca/env
